#set up automatically if launched via launch.sh
ROOT_PATH: '${ROOT_PATH}'
SCRIPT_PATH: '${SCRIPT_PATH}'

MIN_KMER: 1001

HIFI_READS: '/gpfs/gsfs10/users/Phillippy/seq/primate_T2T/PR00251_PPA/raw_data/PacBio_HiFi/*.fasta.gz'

ONT_READS: '/gpfs/gsfs10/users/Phillippy/seq/primate_T2T/PR00251_PPA/raw_data/ont/split/all.100k.split*.fasta.gz'

ONT_COV_THR: 3
ONT_RESOLVE_STEPS: '20 10 5'
